name: Print variables

on: [push, pull_request]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: default run
        run: node index.js
        env:
          INPUT_TOKEN: 'node test input_token'
      - name: print token with node
        uses: ./
        with:
          token: 'node test token'
      - name: print token with echo
        run: |
          echo $TOKEN
        env:
          TOKEN: 'shell test token'
